### ISSUE TITLE
Runtime error when running any office app

### ISSUE THREAD

**Issue by SystematicError** [DonutsBl/office365-pol#11]
Hey! Recently I've been trying my hand at running Office 365. I'm trying to do this based on the general directions given by this repo, but I'm not following them exactly. Here's what I've done so far:

1. Compilde winecx 6.21
2. Created a new wineprefix which is x32 bit and emulating Windows 7
3. Installed the following via winetricks: `riched20, gdiplus, fontsmooth-rgb, vcrun2019, msxml6` (I also tried without `gdiplus` and adding riched20 as just a dll override without installing it and still didn't work)
4. Added the following keys in registry:
```
[HKEY_CURRENT_USER\Software\Wine\EnableUIAutomationCore]
[HKEY_CURRENT_USER\Software\Wine\MSHTML\MainThreadHack]
[HKEY_CURRENT_USER\Software\Wine\EnableOLEQuitFix]
[HKEY_CURRENT_USER\Software\Wine\Direct2D]
"max_version_factory"=dword:00000000
[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
```
5. Ran the x32 bit online installer
6. Added the following dlls:
```
C:\Program Files\Microsoft Office\root\Office16\AppvIsvSubsystems32.dll"
C:\Program Files\Microsoft Office\root\Office16\C2R32.dll"
```

Now after all of this, I cd into `$WINEPREFIX/drive_c/Program Files/Microsoft Office/root/Office16` and run it with winecx which I've added to path (`wine ./WINWORD.EXE`, `wine ./EXCEL.EXE`, etc). However, when I run it, it shows the loading screen and shows this error message afterwards, this still happens even when running via safe mode:

![image](https://user-images.githubusercontent.com/63366086/144624362-4296ec2d-93a7-4ac5-b9e1-b89a241d0844.png)

Am I doing anything wrong? Should I go to winecx 6.20? MS Office 365 worked perfectly fine with the Crossover.

**Comment by DonutsBl** [comment]
I suspect you aren't using the correct Wine version. The last three CrossOver, versions were 21.1.0, 21.0.0 and 20.0.4. The script is designed to work with the version of Winecx that's used with 20.0.4, which is based on Wine version 5.0. You can download the sources for CrossOver 20.0.4's open source components from [https://media.codeweavers.com/pub/crossover/source/crossover-sources-20.0.4.tar.gz](https://media.codeweavers.com/pub/crossover/source/crossover-sources-20.0.4.tar.gz), which include Winecx.

**Comment by SystematicError** [comment]
I retried this using winecx 20.0.4, same error, I did exactly same as I did before except for step 3 I added `riched20` as a dll override (native, builtin) and installed the following via winetricks `allfonts fontsmooth-rgb vcrun2019 msxml6`

**Comment by DonutsBl** [comment]
Have you tried actually using the script?

**Comment by SystematicError** [comment]
No I have been manually following the script instructions as I don't have PlayOnLinux. One thing I forgot to mention is that when compiling instead of using the options `--disable-winedbg --disable-mscms --without-vulkan`, I simply ran `./configure`. I'll look into compiling with these options and then trying out. If that doesn't work I'll try installing and using via pol.

**Comment by DonutsBl** [comment]
Since I've never had this specific problem on any system I tested on and no one who installed using the script seems to have it, I'm closing this issue.

**Comment by DonutsBl** [comment]
Since I've never had this specific problem on any system I tested on and no one who installed using the script seems to have it, I'm closing this issue.
