### ISSUE TITLE
Outlook: Can't log in with Outlook.com account

### ISSUE THREAD

**Issue by DonutsBl** [DonutsBl/office365-pol#4]
If you try to add an Outlook.com e-mail account to Outlook, the login dialog that pops up will just tell you to upgrade your browser  and won't allow you to actually log in.

**Comment by darth-veitcher** [comment]
Have the same issue when attempting to login to an Office account to activate product. Just get the below. Is there a fix?

![image](https://user-images.githubusercontent.com/1722315/143686742-73493bf4-75d8-4684-ac92-4b6e968e01f3.png)

**Comment by DonutsBl** [comment]
None that I know of right know. I tried setting up the account on a Windows computer and than transferring it over, but it seems Outlook detects that the account wasn't set up on the computer you're using and requires you to log in again.

**Comment by DonutsBl** [comment]
I'm closing this issue to merge it with [this one](https://github.com/DonutsBl/office365-pol/issues/10), as they're both talking about the same problem

**Comment by DonutsBl** [comment]
I'm closing this issue to merge it with [this one](https://github.com/DonutsBl/office365-pol/issues/10), as they're both about the same login problem.
